title: Ben Burgess
author: benjburgess
#email: your-email@domain.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  benjburgess.github.io 

#Write an awesome description for your new site here. You can edit this
#line in _config.yml. It will appear in your document head meta (for
#Google search results) and in your feed.xml site description.

# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
#github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

#This code has been added from https://github.com/jekyll/minima/blob/master/_config.yml#L37-L40
# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - data.md
 - multiplestressR.md
 - PageA.md
# - PageB.md note that this page still exists
# - PageC.md note that this page still exists
# - PageD.md note that this page still exists
# - PageE.md note that this page still exists
